name: Deploy Next.js Application to Server

on:
  push:
    branches:
      - main  # Despliega solo cuando haya cambios en la rama `main`

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Chequea el código desde el repositorio
    - name: Checkout code
      uses: actions/checkout@v2

    # 2. Configura Node.js (puedes cambiar la versión según lo necesites)
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.x'  # Cambia la versión de Node.js según tu proyecto

    # 3. Instala las dependencias de tu proyecto
    - name: Install dependencies
      run: npm install

    # 4. Genera la build de la aplicación
    - name: Build the project
      run: npm run build

    # 5. Despliega en el servidor usando SSH
    - name: Deploy via SSH
      uses: appleboy/ssh-action@v0.1.3
      with:
        host: ${{ secrets.SERVER_HOST }}          # Dirección de tu servidor
        username: ${{ secrets.SSH_USER }}         # Usuario de SSH
        key: ${{ secrets.SSH_PRIVATE_KEY }}       # Llave privada SSH (almacenada en GitHub Secrets)
        port: 22                                 # Puerto SSH, cambia si es necesario
        script: |
          cat /var/www/test.txt
